### PR TITLE
Add option to import additional trusted CA certificates

### LINKED ISSUE #28: Certificate Error
Checkmarx is hosted inside the company's Infra with Self-Signed certificates. This action doesn't provide any way to inject certs.

### LINKED ISSUE #52: Please support cxTrustedCertificates from checkmarx-ts/checkmarx-github-action
See here for more details: https://github.com/checkmarx-ts/checkmarx-github-action#inputs-for-actions-scan-asyncscan

This ticket could be an add-on to #28 . If this feature wasn't implemented we'd be forced to use the deprecated action that has this feature.

Currently, I am seeing this below when trying to run the scan against our on-prem checkmarx:
```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "***/cxrestapi/auth/identity/connect/token": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at com.checkmarx.sdk.service.CxAuthService.getAuthToken(CxAuthService.java:99)
	at com.checkmarx.sdk.service.CxAuthService.getAuthToken(CxAuthService.java:62)
	at com.checkmarx.sdk.service.CxAuthService.createAuthHeaders(CxAuthService.java:237)
	at com.checkmarx.sdk.service.CxService.getTeamId(CxService.java:1455)
	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineOwnerId(ScanRequestConverter.java:123)
	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineTeamAndOwnerID(ScanRequestConverter.java:87)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:246)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:317)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:201)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:590)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:649)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:590)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:463)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:93)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:3[69](https://vghe.verint.com/XM-Reporting/vcp-platformbi-export-api/runs/19902?check_suite_focus=true#step:7:69))
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:87)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776)
	... 36 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:2[71](https://vghe.verint.com/XM-Reporting/vcp-platformbi-export-api/runs/19902?check_suite_focus=true#step:7:71))
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 62 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:2[80](https://vghe.verint.com/XM-Reporting/vcp-platformbi-export-api/runs/19902?check_suite_focus=true#step:7:80))
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 68 common frames omitted
```

### PR DESCRIPTION
**Pull request by mark-strasser-nnl**
Fixes #52 
Fixes #28 

Supports the ability to import certificate files allowing for self-signed certificate chain.  Many security-conscious organizations use self-signed certificate chains.

Note: this does not *replace* the existing `cacerts` file.  Rather, this imports additional certificates into the Java keystore.

## Fixes
The following exception is thrown when starting CxFlow without the extra certificates.

> org.springframework.web.client.ResourceAccessException: I/O error on POST request for "***/cxrestapi/auth/identity/connect/token": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

## Changes
1. Adds copy of new bash script `keytool-import-certs.sh` to `Dockerfile`
2. Adds new input option `extra_certificates` and `EXTRA_CERTIFICATES` to `action.yml`.
3. Modifies `entrypoint.sh` to run the script if `EXTRA_CERTIFICATES` is non-empty.

## Discussion 
- Using the previous action's `cxTrustedCertificates` option is not secure.  It's similar to `curl --insecure` in that it's susceptible to DNS spoofing and redirection.
- The fix is specific to Java 8 keystore location and keytool options.  If the base image is upgraded / change to Java 11 or 17, this path would need to change.
- I didn't add a test, but I can add one if needed.  Manual testing does work.

### CODE REVIEW

**Comment by mark-strasser-nnl** [comment]
@satyamchaurasiapersistent - let me know if you have any questions or issues with the changes.

**Comment by ffeldmann** [comment]
@mark-strasser-nnl  looking forward for this PR to be merged, thanks for your work!

**Comment by mark-strasser-nnl** [comment]
@satyamchaurasiapersistent - will you be able to look at this PR in the next week or two?

**Comment by mark-strasser-nnl** [comment]
@james-bostock-cx - can you ping satyam?  This ticket has been open for more than a week with no comments yet.  I'm interested in starting the discussion on what is needed to integrate this change through.  If it helps, I can provide a customer ID or file a Checkmarx support ticket.

**Comment by satyamchaurasiapersistent** [comment]
hi @mark-strasser-nnl in shell script file jvm_keystore="/etc/ssl/certs/java/cacerts" should be taken as argument because keystores can be override. By making this as hardcoded it's not a generic solution.

**Comment by mark-strasser-nnl** [comment]
> jvm_keystore="/etc/ssl/certs/java/cacerts" should be taken as argument

Done.  `entrypoint.sh` now passes the keystore path as an argument to the script.  

Did you mean this should be a user-specified  input option in `action.yml`?  If so, that's too implementation-specific for the caller - they would have to know which path to pass in, when it really varies based on the container image used.

This is one case where the caller should only worry about passing in the extra certificates, and not about the particular container image.  If the image changes, so should the path.  IMO, the caller shouldn't have to update the certificate keystore path based on which container image is being run behind the scenes.

---

> Key Store Default Path Should be /usr/local/openjdk-8/jre/lib/security/cacerts

That path did not work.  I got the following error when running:

```
Importing custom certificates in certificates subdirectory to '/usr/local/openjdk-8/jre/lib/security/cacerts'
importing cert /github/workspace/certificates/checkmarx-dev.unrpnet.gov.crt
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /usr/local/openjdk-8/jre/lib/security/cacerts (No such file or directory)
```

Using the keystore path indicated in [this comment](https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/issues/28#issuecomment-967424463) worked:

```
Importing custom certificates in certificates subdirectory to '/etc/ssl/certs/java/cacerts'
importing cert /github/workspace/certificates/checkmarx-dev.unrpnet.gov.crt
Certificate was added to keystore
```

Thanks for the feedback so far, looking forward to chatting with you more @satyamchaurasiapersistent !

**Comment by mark-strasser-nnl** [comment]
Closing - independently merged to `master` as [commit 2e2ff2e](https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/commit/2e2ff2e3963f7ee3bba923813b92010f8477000f).

I'll test it out shortly - thanks @satyamchaurasiapersistent

**Comment by mark-strasser-nnl** [comment]
Testing worked.  


For future reference, my GitHub Actions workflow job looks like:

```yaml
  static-code-analysis:
    runs-on: [self-hosted]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    # check out repo containing .crt files
    - name: Checkout certificates
      uses: actions/checkout@v3
      with:
        repository: myorg/myorg-public-certificates
        path: certificates
      
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@master # TODO switch to version branch
      with:
        project: software # <-- Insert Checkmarx SAST Project Name
        team: CxServer
        checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        checkmarx_username: ${{ secrets.CHECKMARX_USER }} # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.
        extra_certificates: certificates # must be relative path to $GITHUB_WORKSPACE
        break_build: false
        scanners: sast
        bug_tracker: Sarif
        incremental: false
        params: --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --cx-flow.filterSeverity --cx-flow.filterCategory --checkmarx.disable-clubbing=true
```

**Comment by satyamchaurasiapersistent** [comment]
Hi @mark-strasser-nnl  I have made some changes and it's working fine please make below changes and test at your end so that i can merge this PR.

JAVA_home could be at different location for self hosted runners so we have made this flexible and default value we are considering as /etc/ssl/certs/java/cacerts
image

Add this in documentation 
image
There was some permission issue at cloud so we have changed in this file as well
image
Added below environment variable as well
image
image
Here we are passing environment variable in entrypoin
image



Thanks for your contribution.

**Comment by mark-strasser-nnl** [comment]
> JAVA_home could be at different location for self hosted runners 

Apologies if I am not understanding here or communicating clearly.

This keytool cacerts path is *not* a path on our self-hosted runner.  Our self-hosted runer already has self-signed certificate authorities defined in this location.  The action correctly ignores the files on the self-hosted runner.

Instead, the path is the [`cacerts` keystore](https://docs.microfocus.com/SM/9.52/Hybrid/Content/security/concepts/what_is_a_cacerts_file.htm) *in the Docker container image* used by this action.  Per the [`Dockerfile`](https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/blob/master/Dockerfile#L2C1-L2C23), the base image is:

```Dockerfile
FROM checkmarx/cx-flow
```

This image has Java installed, which uses the listed `cacerts` keystore.  The changes I made allow the image to be modified *at `docker build` time* and also at *`docker run` time* using the script `keytool-import-certs.sh`.

Do you want an action input option to tell you where `cacerts` is located in the `checkmarx/cx-flow` container?  What use case / scenario do you see for users specifying where the `cacerts` file is located in the Docker image?

**Pull request merged**
